version: '3.8'

services:
  web:
    build: ./code
    command: python wsgi.py run -h 127.0.0.1
    volumes:
      - ./code:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_HOST=postgresql
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgresql
      - POSTGRES_PORT=5432
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    container_name: postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgresql

volumes:
  postgres_data: